### ISSUE TITLE
Redundancy

### ISSUE THREAD

**Issue by RonaldColyar** [JanHolger/pyogpclient#1]
From line 208 -221 You repeat logic. You could simplify it into one function and constantly re-call it. Cool project!! @JanHolger  

https://github.com/JanHolger/pyogpclient/blob/master/pyogpclient/OGPClient.py

**Comment by RonaldColyar** [comment]
@JanHolger

**Comment by JanHolger** [comment]
This is just "not yet implemented" logic so the methods return an empty list instead of the parsed player/team/rule/whatever list. I didn't implement those because the game that i made this for (Onset) doesn't support those fields anyway. If someone wants to use this for their HL 1, BF BC2 or JC2 server i can still implement those methods. This protocol is dead for almost 2 decades now (for a good reason...) and for some weird reason a single dev decided to use this b.s. protocol in his game. It's my first real world python project and python really sucks even more than i was remembering so i'll probably never touch this project again :D

**Comment by RonaldColyar** [comment]
lmfaoooooooooooooo just disrespect my baby :(
